[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
on_ft = ['python', 'python3']

[[plugin]]
repo = 'prabirshrestha/vim-lsp'
